# Generated by Django 4.1.7 on 2023-04-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
