# Generated by Django 4.1.7 on 2023-05-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker', models.CharField(max_length=64)),
                ('attack_status', models.BooleanField()),
                ('protector', models.CharField(max_length=64)),
                ('damage', models.IntegerField()),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='log',
        ),
    ]
