# Generated by Django 4.1.7 on 2023-05-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_battle_log_delete_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='levels',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
