# Generated by Django 4.1.7 on 2023-05-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_character_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='energy',
            field=models.IntegerField(default=500),
        ),
    ]
